### PR TITLE
Add documentation to the repository

### PR DESCRIPTION
**Pull request by 12rambau**
This PR propose a first draft of a built-in documentation. As mentioned in https://github.com/openforis/sepal-doc/issues/300, I think GWB documentation should not rely on third party (in this case SEPAL) to host its technical documentation. Even more when the SEPAl team don't manage to keep up with the release pace make us out of sync with latest improvements. 

In this PR I drafted a first documentation. To build it: 
- install nox by running `$ pip install nox`
- build the documentation by running the `$ nox` from the "docs" folder. 
- open the "docs/_build/html/index.html" file to see the result in your browser

## Question: 

Are you interested ? 

## If yes

- [x] Could you help me write a installation process page (It's not mentioned in the SEPAL documentation)
- [x] How would you like to deploy it ? (Github pages and RDT are the 2 sane options but need the owner of the repository agreement to set up)
- [x] I still need to integrate the modification you send me via mail
- [ ] Do you have any comment on the format I chose ?

### CODE REVIEW

**Comment by vogtpet** [comment]
I cannot merge this PR because it is in draft or should I use the command line instructions to merge?  Once I have it, I will try to build it via nox as you suggested and see if it works here.
- deploy: Github pages or RDT, no idea, whatever works is fine
- modifications: I can update all sections to their latest version, please don't waste your time on that, same for the installation process (the point for moving it here is that I no longer have to bother you updating the documentation)
- comment on format: no comment yet because I can't see things yet but trust you that it is ok

**Comment by 12rambau** [comment]
I released the draft lock you can merge as soon as you like

**Comment by vogtpet** [comment]
Awesome, great job! Thank you so much!!
I will update everything in the next days. After that I need to figure out how to publish it, I can ask a colleague here or may have to come back to you. Thanks again, this is great and really much appreciated!!

**Comment by 12rambau** [comment]
If you/JRC is ok with it requires 6 lines of code to publish it on RDT (GitHub does not require to register to another service but require a bit more work), let me know when you are happy with the doc I'll send you guidance or directly the .readthedocs?yml file in a PR

**Comment by vogtpet** [comment]
RDT is fine for us. I'm progressing well on updating the documentation but maybe you could send me the yml file already now so I can test the entire update chain? If that works then I will let you know when the documentation is final, already for the upcoming version 1.9.1.

**Comment by 12rambau** [comment]
let me open an extra PR with the file

**Pull request merged**
