### PR TITLE
add readthedocs config

### PR DESCRIPTION
**Pull request by 12rambau**
Normally with this file, if you wire the repository to your readTheDocs account, the build should start automatically and produce an html website.

Let me know if you need guidances to create the RDT hook

### CODE REVIEW

**Comment by vogtpet** [comment]
hmm, signed up at RTD and associated my project to it. RTD builds ok but I just get an empty [website](https://gwb-doc.readthedocs.io/en/latest/#) 
Probably made a wrong assignment?

**Comment by 12rambau** [comment]
That's normal I checked your project and you associated the wrong repositoy. The hook is wired to https://github.com/vogtpet/gwb.git instead of https://github.com/ec-jrc/GWB

**Comment by vogtpet** [comment]
I don't understand this: I am logged into GitHub and can easily add/modify the repo  [https://github.com/ec-jrc/GWB](https://github.com/ec-jrc/GWB). But when I list my repos by clicking on my logo at the top right, I do not see this repo but instead 2 other repo on my private GitHub account [https://github.com/vogtpet/](https://github.com/vogtpet/), see attached. 
In my RTD account, I also only see these 2 repos from my private account and if if try to manually add my work account repo, RTD tells me the project already exists, see attached.
my_repos

RTD

**Comment by 12rambau** [comment]
it's because only the "admins" of the repository can add the RDT hook and it seems you're not owning this one. My guess is IT service have ownership and you need to ask them to make you at least "admin" so that you can see the repository in the RDT discovery list.

**Comment by vogtpet** [comment]
Thanks for this info, which makes good sense. I will ask them and then get back to you. Thanks!

**Comment by vogtpet** [comment]
After some tinkering, and good help from a colleague, I managed to find a workaround to get RTD working, the GWB manual website is now [online](https://gwbdoc.readthedocs.io). Please note that this is a first preview and I still need to update some pages for the upcoming GWB version 1.9.1. I will let you know when it is ready. If you have any suggestions, please let me know. And a big thanks once more for doing the major part of this job!

**Comment by 12rambau** [comment]
that's perfect, I'm going to drop the one we store in sepal-doc and point here for the CLI tool, as it's way better looking here. I'll ping you as a reviewer.

**Comment by vogtpet** [comment]
I added an acknowledgement to you and Loïc for helping me to get this website working. I still need to do a bit more fine-tuning on this website, which I will commit in 1-2 days. Please note that this document describes the upcoming GWB version 1.9.1, which will be released in ~ 2 weeks. There is no harm to show this info earlier but maybe you want to wait  until the final release of 1.9.1 before redirecting to the new website? 
Also note that GWB version 1.9.1 includes the bash script `/opt/GWB/tools/GWBupdate_deb.sh` which when run from a root terminal will check for and if available automatically download/verify/upgrade to a potential newer version of  GWB. This script could then be included in a cron-job and run for example weekly to ensure to always have the latest GWB version installed on Sepal without doing any manual maintenance.

**Comment by 12rambau** [comment]
Thanks for your update, ping me when you are done with your modifications and I'll merge https://github.com/openforis/sepal-doc/pull/314. 
I think we will stick with the manual update on our side to keep track of our changes and update the application in time (this is what we do with other, better to keep control rather than loose track of what is happening in our deps)

**Comment by vogtpet** [comment]
Still face some issues with having the WebHook work properly, but hope to get this fixed in the next days. The preliminary [website](https://gwbdoc.readthedocs.io/) version is now online, with the Acknowledgements on the first page and all modules completed. I will let you know when all is working and complete. If you have any comments on the website, please let me know so I can include them.

**Pull request merged**
